const cool = {
    id: 'ch_1MAvM9BMfu7cMOV8YomCCDWg',
    object: 'charge',
    amount: 2000,
    amount_captured: 2000,
    amount_refunded: 0,
    application: null,
    application_fee: null,
    application_fee_amount: null,
    balance_transaction: 'txn_1MAvMABMfu7cMOV8rzuIORPI',
    billing_details: {
        address: {
            city: null,
            country: 'IN',
            line1: null,
            line2: null,
            postal_code: null,
            state: null
        },
        email: 'dsfsfd@gmail.com',
        name: 'sfdfds',
        phone: null
    },
    calculated_statement_descriptor: 'ZUBSTR',
    captured: true,
    created: 1670072533,
    currency: 'inr',
    customer: null,
    description: null,
    destination: null,
    dispute: null,
    disputed: false,
    failure_balance_transaction: null,
    failure_code: null,
    failure_message: null,
    fraud_details: {},
    invoice: null,
    livemode: false,
    metadata: {
        createdAt: '1670072508763',
        userId: 'string',
        transactionId: 'a17db67e-754d-43c3-9619-3f3d8ec6efde'
    },
    on_behalf_of: null,
    order: null,
    outcome: {
        network_status: 'approved_by_network',
        reason: null,
        risk_level: 'normal',
        risk_score: 3,
        seller_message: 'Payment complete.',
        type: 'authorized'
    },
    paid: true,
    payment_intent: 'pi_1MAvM9BMfu7cMOV8c1Yugwbv',
    payment_method: 'pm_1MAvM8BMfu7cMOV8ZauE5TlZ',
    payment_method_details: {
        card: {
            brand: 'visa',
            checks: [Object],
            country: 'US',
            exp_month: 5,
            exp_year: 2045,
            fingerprint: 'f4DWNQLJXV71lOvs',
            funding: 'credit',
            installments: null,
            last4: '4242',
            mandate: null,
            network: 'visa',
            three_d_secure: null,
            wallet: null
        },
        type: 'card'
    },
    receipt_email: null,
    receipt_number: null,
    receipt_url: 'https://pay.stripe.com/receipts/payment/CAcaFwoVYWNjdF8xRlRvWjdCTWZ1N2NNT1Y4KNeRrZwGMgaZsZrvpmM6LBaSlPLJbqUel1_t4r_MJ7Qg1f9JXmz9iDKrIjQz4miI8g6yz0mKjfyv6qEZ',
    refunded: false,
    refunds: {
        object: 'list',
        data: [],
        has_more: false,
        total_count: 0,
        url: '/v1/charges/ch_1MAvM9BMfu7cMOV8YomCCDWg/refunds'
    },
    review: null,
    shipping: null,
    source: null,
    source_transfer: null,
    statement_descriptor: null,
    statement_descriptor_suffix: null,
    status: 'succeeded',
    transfer_data: null,
    transfer_group: null
}